pretrained_model_path: "/data/jianglifan/CompVis/stable-diffusion-v1-4"
output_dir: "./output/turn_to_smile"

train_data:
  video_root: "./train_data/videos/turn_to_smile"
  prompt: "turn to smile"
  n_sample_frames: 16
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  image_path: "benchmark/turn_to_smile"
  prompts:
    - "a panda, head photo"
    - "a beautiful lady"
    - "a handsome man"
  video_length: 16
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 25000
checkpointing_steps: 5000
validation_steps: 1000
trainable_modules:
  - "conv1d"
  - "conv_gate"
  - "attn1.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
